### PR TITLE
Fixes #228 Highlighted errors

### LINKED ISSUE #228: Color of 'This field is required' error
The color of 'This field is required' message should be RED to be more eye catching.

Before:
image

After:
image

(a GSoC aspirant)

### PR DESCRIPTION
**Pull request by sreejakshetty**
In reference to issue #228 . changed color of fields and boxes

### CODE REVIEW

**Comment by medhach** [comment]
@kamishettysreeja25 I would suggest you to find out if no one else is working on the issues before you submit a PR next time. Please resolve your conflicts.

**Comment by sreejakshetty** [comment]
@medhach I will make sure next time.
Currently the Travis CI has passed and there are no merge conflicts.

**Comment by medhach** [comment]
Could you recheck?

**Comment by sreejakshetty** [comment]
@medhach done.

**Pull request closed without merging**
