### PR TITLE
Reset button added to edit profile (Issue #167)

### PR DESCRIPTION
**Pull request by yatna**
Reset button resets data to previous value
screenshot from 2017-05-19 19 29 11

### CODE REVIEW

**Comment by GunpreetAhuja** [comment]
The change in the button size would affect the buttons on several other pages. Have you checked them?

**Comment by yatna** [comment]
@GunpreetAhuja Yes, I have on my side.

**Comment by GunpreetAhuja** [comment]
One more thing, you actually do not need to make it a submit button, a reset type button does its task itself.

**Comment by yatna** [comment]
@GunpreetAhuja It is not a submit button. It is actually an anchor tag which has been given a btn class to get the layout which resembles to a button. Submit button was already present for submitting the form.

**Comment by GunpreetAhuja** [comment]
I used that just as a reference, although my point stays the same.

**Comment by yatna** [comment]
Fixed in another PR

**Pull request closed without merging**
