### PR TITLE
Fix for #21 and #22

### PR DESCRIPTION
**Pull request by mish24**
Improved UI to display buttons properly on small screens and added minor edits

### CODE REVIEW

**Comment by medhach** [comment]
@mish24 Could you add a Screenshot of the changes?

**Comment by mish24** [comment]
screenshot from 2017-02-08 10-40-46
screenshot from 2017-02-08 10-41-02
screenshot from 2017-02-08 10-41-08

This fixes issue #21 and #22. Please have a look @medhach :)

**Comment by mish24** [comment]
screenshot from 2017-02-08 10-53-41

The homepage after logging out is also fixed. @medhach I changed some colours too, are they fine?

**Comment by medhach** [comment]
@mish24 Could you squash your commits with a proper commit message? I will merge it soon. Good work! :)

**Comment by mish24** [comment]
@medhach Uh I guess I made a huge blunder while doing this squashing. I'll send a new pull request asap. Sorry :(

**Comment by mish24** [comment]
Refer to #84 for the changes. :)

**Pull request closed without merging**
