### PR TITLE
Removed trailing p tag

### LINKED ISSUE #349: Remove trailing "p" tag
## Description
Remove trailing "p" tag on post display in view post. 

## Mocks

trailing_p_tag

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

### PR DESCRIPTION
**Pull request by valerycodes**
### Description
Removed the <p> that showed at the start and end of each post description in view mode

Fixes #349 

### Type of Change:
**Delete irrelevant options.**

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

### CODE REVIEW

**Review by sara-02 — COMMENTED** [review]
@valeriecodes LGTM.
I just have a doubt thought, as per the Django template 
here https://docs.djangoproject.com/en/2.0/ref/templates/builtins/#safe
It is not a good idea to chain other filters after `safe`. Are we still good? Or should we look into `safeseq` ? https://docs.djangoproject.com/en/2.0/ref/templates/builtins/#safeseq

**Comment by valerycodes** [comment]
@sara-02 I have made the change. i.e. replaced safe filter with safeseq

**Comment by sara-02** [comment]
@valerycodes thanks. Is there is way to test these locally once, before merging. Or can you place a screenshot of your latest changes showing the correct display without the `<p>` tag. 
Let us make sure we close this issue once and for all :)
Would be great if you could update the PR description with the updated scree shot :)

**Comment by sara-02** [comment]
@valerycodes You will also be required to squash your commits, once before we finally merge this.

**Comment by valerycodes** [comment]
@sara-02 the safeseq filter doesn't do the work per say. Didn't clear my cache. 
My bad! :pray: 
I suggest we should revert back to the safe filter

## safeseq Result
safeseq

**Comment by sara-02** [comment]
@valerycodes Yes, looks like things got even worse. Good thing we checked!
Please revert to using `safe`. And please share a screenshot of that as well. Let us be double sure :)

**Comment by valerycodes** [comment]
@sara-02 I have reverted to safe filter
## safe filter Result
safe

**Comment by sara-02** [comment]
@valeriecodes LGTM :)

**Comment by sara-02** [comment]
@medhach we can merge this now.

**Pull request merged**
