### PR TITLE
Added FirstAide logo to dashboard  (Issue #59)

### PR DESCRIPTION
**Pull request by yatna**
1. Added FirstAide's logo.
2. Changed Title and button's text from 'PCSA' to 'FirstAide' ( As the name has been officially changed)
3. Added Bootstrap thumbnail class to images giving them a nice border.

screenshot from 2017-02-10 19 56 39

### CODE REVIEW

**Comment by mish24** [comment]
@yatna I was already assigned to work on this issue :) And I've added the work in issue #88

**Comment by yatna** [comment]
@mish24 Oh, sorry I did not know. You can take the part of adding the image. I will remove that part from the PR :-)

**Comment by mish24** [comment]
No problem :). Also, refer to #88 PR and suggest any changes if you can. That'll be of great help

**Comment by yatna** [comment]
@medhach Merge conflicts resolved. Since, I created this PR directly from the Github UI, I cannot squash the commits. Also, the second commit fixes a typo, hence it is not totally useless and can be considered performing a task. If possible merge it this way, otherwise I can send a fresh PR.

**Comment by medhach** [comment]
@yatna A new PR would be appreciated.

**Pull request closed without merging**
