### PR TITLE
Fixed the 'Cancel' button on edit profile. (bug #156)

### PR DESCRIPTION
**Pull request by mish24**
Initially 'Update' and 'Cancel' on edit profile page did the same thing. This PR fixes that with javascript so that the text whixh was changed is also cleared, and the speed is also improved. 
@medhach Please review

### CODE REVIEW

**Comment by yatna** [comment]
@mish24 Hey, I claimed the issue through #149. I think you missed it :-D

**Comment by mish24** [comment]
@yatna Hey, yeah I did. I'll close my PR and issue :)

**Comment by yatna** [comment]
@mish24 Using the window history to create a 'Cancel' Button is not a good practice and should be avoided. It can be a bug in itself.

**Steps to reproduce the bug** -
Open http://localhost:8000/edit_profile_page/?id=1 in a new tab. (Replace 1 according to the user's id). It will open the edit profile page.
Click the 'Cancel' Button.

**RESULT**- It won't work.

**REASON-** Since, you have used a new tab, you dont have any previous history. Hence, the cancel button has no where to go and it will be disabled.

A better solution would be to fix the button by removing the < button > tag ( as in #164 ) or using a separate view to redirect.

**Comment by mish24** [comment]
@yatna Yeah that makes sense. Understood. :)

**Pull request closed without merging**
