### PR TITLE
added radio buttons for gender in profile

### PR DESCRIPTION
**Pull request by mish24**
Added an option to enter the gender. Maintains uniformity. @medhach Please have a look.

### CODE REVIEW

**Comment by medhach** [comment]
@mish24 A screenshot of the changes with the pull requests would be appreciated. :)

**Comment by mish24** [comment]
screenshot from 2017-02-07 10-27-34

@medhach I'll take care from next time!

**Comment by medhach** [comment]
Good job! Merging your request!

**Comment by Neetuj** [comment]
should we have a "prefer not to say" option? to be inclusive?

**Comment by medhach** [comment]
That's a good idea. Will add it!

**Comment by mish24** [comment]
@Neetuj @medhach There won't be any situation where we might need to filter users based on gender, right?

**Pull request merged**
