### PR TITLE
Updated Installation Guide to prevent DB errors

### PR DESCRIPTION
**Pull request by yatna**
Added 'allauth' to makemigrations app and removed 'signup'

### CODE REVIEW

**Comment by GunpreetAhuja** [comment]
We do not need to add allauth to makemigrations, it is done by default.

**Comment by yatna** [comment]
It was giving a 'relation not found' when not included. 
BTW do you use 'python manage.py makemigrations' or python 'manage.py makemigrations all_app_names' while making migrations.

**Comment by GunpreetAhuja** [comment]
I do not get this error even without explicitly migrating the allauth or social_django app.

**Comment by amittbhardwj** [comment]
@yatna the  apps installed through pip doesn't need to be included in the makemigrations command as migrate will automatically include external packages like allauth and social_django.

**Pull request closed without merging**
