### PR TITLE
Restricted Pcusers from changing e-mail ids

### PR DESCRIPTION
**Pull request by mish24**

### CODE REVIEW

**Comment by GunpreetAhuja** [comment]
I think they should be allowed to change email ID in case the user wants to switch to another email. Instead the verification of the email should be taken care of.

**Comment by mish24** [comment]
@GunpreetAhuja Putting it in edit profile doesn't make sense. It won't change the email id, because the pcuser is linked with the user. Even if you try to edit the id, it'll remain same.

**Comment by HarinderKaur11** [comment]
@mish24 We can edit email id of user also but the code for that is missing.

**Comment by mish24** [comment]
Solves issue #175

**Comment by HarinderKaur11** [comment]
@mish24 we are not questioning your PR, just giving our point of view and we understand that it makes no sense to have a field in which we cannot edit. :)

**Pull request closed without merging**
