### PR TITLE
Placeholder now shows different message for changing password

### PR DESCRIPTION
**Pull request by mish24**
screenshot from 2017-02-22 11-16-53
screenshot from 2017-02-22 11-17-59

Minor edit. Fixes the message which placeholder showed before.

### CODE REVIEW

**Comment by mish24** [comment]
@medhach I also made the header show the username created directly while creating admin. Since only one Pcuser is linked with any user, I don't think this should be a problem. Is it fine?

**Comment by medhach** [comment]
Can you squash the commits and have one message that explains both the changes?

**Comment by mish24** [comment]
@medhach Done :)

**Comment by mish24** [comment]
@medhach I again made a blunder while force pushing. Please close this PR. I'll resend a similar one again

**Pull request closed without merging**
