### PR TITLE
Fixed the 'forgot password' (issue #186)

### PR DESCRIPTION
**Pull request by mish24**
Fixes issue #186.
The view has been fixed. The email cannot be sent as the 'website' has been set to the deployment website. @medhach Please review :)
screenshot from 2017-03-11 05-43-43

### CODE REVIEW

**Comment by medhach** [comment]
@mish24 Can you change the buttons to a different color and size?

**Comment by mish24** [comment]
@medhach Okay I will fix the sizes and colors. Green for 'Email me' and red for 'Cancel'??

**Comment by medhach** [comment]
@mish24 Yeah thats a good idea!

**Comment by mish24** [comment]
@medhach  Alright then!

**Comment by mish24** [comment]
forgot_password
@medhach How's this?? Shall I make the other buttons similar too?

**Comment by medhach** [comment]
Isn't this too bright on the page @mish24 ? Could you use sober shades of green and red just to see how it may look?

**Comment by mish24** [comment]
@medhach Yeah, I'll try more subtle colors are get back.

**Comment by GunpreetAhuja** [comment]
@medhach I think same color buttons usually look better when it comes to a single page.

**Pull request closed without merging**
