### PR TITLE
sorted imports

### LINKED ISSUE #114: Alphabetical Imports ( PEP8 style guide)
https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/

All the imports needs to be alphabetically sorted as mentioned in PEP8 style guide. 

@medhach I am sending a PR ?

### PR DESCRIPTION
**Pull request by muddlebee**
fixed #114 

@medhach please review

### CODE REVIEW

**Comment by muddlebee** [comment]
@medhach please merge before it creates more conflicts :P 
conflicts resolved

**Comment by muddlebee** [comment]
Final Changes done. Please review.
And not able to squash. PR becomes weird

**Comment by medhach** [comment]
Could you elaborate? Maybe I could help with that.

**Comment by muddlebee** [comment]
@medhach there were some conflicts with this PR. so I fixed it. But commits of previously merged PR also comes up with this PR when I squash. Is that okay ?

**Pull request closed without merging**
