### PR TITLE
better layout for buttons

### PR DESCRIPTION
**Pull request by muddlebee**
fixes a part of #70 
@medhach please review 
screenshot from 2017-02-25 22 06 19

### CODE REVIEW

**Comment by muddlebee** [comment]
Previously : 
screenshot from 2017-02-25 22 09 08

**Comment by medhach** [comment]
Could we have a same color for both buttons? Maybe something that goes with the page?

**Comment by muddlebee** [comment]
screenshot from 2017-02-27 21 48 11

@medhach is this good ? . Either way UI is going to be revamped.

**Comment by medhach** [comment]
I'm sorry but can you try grey? or navy blue, like the Peace Corps logo?

**Comment by muddlebee** [comment]
@medhach changed the colour please review

**Comment by muddlebee** [comment]
screenshot from 2017-02-28 23 49 29

@medhach see the ss

**Pull request merged**
