### PR TITLE
Rename infohub Django app to macc

### LINKED ISSUE #15: Rename infohub Django app to macc
Rename infohub (the app that contains project settings) to macc, since MACC is the name of the project.

### PR DESCRIPTION
**Pull request by muddlebee**
fixes #15

### CODE REVIEW

**Comment by muddlebee** [comment]
@medhach please if the PR #74 is right merge it first. Because this PR is dependent on it. As I have made some changes in travis file please merge that before you merge this to avoid conflicts :)

**Comment by medhach** [comment]
@anweshknayak Squash your commits. :)

**Comment by muddlebee** [comment]
@medhach please review. It is squashed into this commit. Closing the rest PRs

**Comment by anweshknayak** [comment]
@medhach I have removed PR #13 for now. It needs some improvement. Please check the rest

**Comment by muddlebee** [comment]
@medhach squashing commits done.

**Pull request closed without merging**
